before:
  hooks:
  - go mod download
builds:
- main: .
  binary: health-cli
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - "386"
  - amd64
  - arm
  - arm64
  - ppc64le
  - s390x
  ignore:
  - goos: darwin
    goarch: "386"
  goarm: [6]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
